hazard_model_ids = ["SLT_v8_gmm_v2_FINAL"]
site_list = "NZ_0_1_NB_1_1"
vs30s = [400,750,250,600,350,175,300,450,375,275,225,200,150]
poes = [0.1, 0.02]
imts = ["PGA","SA(0.1)", "SA(0.2)", "SA(0.3)", "SA(0.4)", "SA(0.5)", "SA(0.7)","SA(1.0)", "SA(1.5)", "SA(2.0)", "SA(3.0)", "SA(4.0)", "SA(5.0)", "SA(6.0)","SA(7.5)", "SA(10.0)" ]
aggs = ["mean", "0.1", "0.2", "0.5", "0.8", "0.9"]

